name: release

permissions:
  contents: write
  packages: write

on:
  release:
    types:
      - released

env:
  CARGO_TERM_COLOR: always

jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      -
        name: login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: free disk space (ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # 1.3.1
        with:
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          swap-storage: false
      -
        name: build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
  
  release-binaries:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: rust compilation prerequisites
        run: |
          sudo apt update
          sudo apt install -y \
            protobuf-compiler
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src
      -
        name: run build
        run: cargo build --locked --release
        timeout-minutes: 90
      -
        name: record artifact checksums
        run: |
          sha256sum target/release/evolute-node | cut -d ' ' -f 1 > target/release/evolute-node.sha256
          sha256sum target/release/wbuild/evolute-runtime/evolute_runtime.compact.compressed.wasm | cut -d ' ' -f 1 > target/release/wbuild/evolute-runtime/evolute_runtime.compact.compressed.wasm.sha256
      -
        name: publish release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/evolute-node
            target/release/evolute-node.sha256
            target/release/wbuild/evolute-runtime/evolute_runtime.compact.compressed.wasm
            target/release/wbuild/evolute-runtime/evolute_runtime.compact.compressed.wasm.sha256
